CREATE TABLE sc_spmobil_loginevents (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id NUMBER(19) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    platform NUMBER(5) NOT NULL,       -- 1=ios, 2=android
    app_version VARCHAR2(255),
    os_version VARCHAR2(255),
    ip_address VARCHAR2(45),           -- pour stocker IPv4 ou IPv6
    country_code CHAR(2),
    device VARCHAR2(45),

    PRIMARY KEY (id, occurred_at)
);